ALTER TABLE `products` CHANGE `title` `title` VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `products` CHANGE `cod_int` `cod_int` VARCHAR(20) NOT NULL;
ALTER TABLE `products` CHANGE `cod_ext` `cod_ext` VARCHAR(20) NULL DEFAULT NULL;
ALTER TABLE `sell_items` CHANGE `icms` `icms` DECIMAL(10,2) NULL;
ALTER TABLE `sell_items` CHANGE `icmssubst` `icmssubst` DECIMAL(10,2) NULL;
ALTER TABLE `sell_items` CHANGE `ipi` `ipi` DECIMAL(10,2) NULL;
ALTER TABLE `sell_items` CHANGE `vlunity` `vlunity` DECIMAL(10,4) NULL;
ALTER TABLE `sell_items` CHANGE `vldiscount` `vldiscount` DECIMAL(10,2) NULL;
ALTER TABLE `sell_items` CHANGE `vltotal` `vltotal` DECIMAL(10,2) NULL;
ALTER TABLE `purchase_items` CHANGE `icms` `icms` DECIMAL(10,2) NULL;
ALTER TABLE `purchase_items` CHANGE `icmssubst` `icmssubst` DECIMAL(10,2) NULL;
ALTER TABLE `purchase_items` CHANGE `ipi` `ipi` DECIMAL(10,2) NULL;
ALTER TABLE `purchase_items` CHANGE `vlunity` `vlunity` DECIMAL(10,4) NULL;
ALTER TABLE `purchase_items` CHANGE `vldiscount` `vldiscount` DECIMAL(10,2) NULL;
ALTER TABLE `purchase_items` CHANGE `vltotal` `vltotal` DECIMAL(10,2) NULL;
ALTER TABLE `sells` CHANGE `totalicms` `totalicms` DECIMAL(20,2) NULL;
ALTER TABLE `sells` CHANGE `totalicmssubst` `totalicmssubst` DECIMAL(20,2) NULL;
ALTER TABLE `sells` CHANGE `totalipi` `totalipi` DECIMAL(20,2) NULL;
ALTER TABLE `sells` CHANGE `totalfreight` `totalfreight` DECIMAL(20,2) NULL;
ALTER TABLE `sells` CHANGE `grandtotal` `grandtotal` DECIMAL(20,2) NULL;
ALTER TABLE `sells` CHANGE `totaldiscount` `totaldiscount` DECIMAL(20,2) NULL;
ALTER TABLE `purchases` CHANGE `totalicms` `totalicms` DECIMAL(20,2) NULL;
ALTER TABLE `purchases` CHANGE `totalicmssubst` `totalicmssubst` DECIMAL(20,2) NULL;
ALTER TABLE `purchases` CHANGE `totalipi` `totalipi` DECIMAL(20,2) NULL;
ALTER TABLE `purchases` CHANGE `totalfreight` `totalfreight` DECIMAL(20,2) NULL;
ALTER TABLE `purchases` CHANGE `grandtotal` `grandtotal` DECIMAL(20,2) NULL;
ALTER TABLE `purchases` CHANGE `totaldiscount` `totaldiscount` DECIMAL(20,2) NULL;
ALTER TABLE `sells` CHANGE `paymenttype` `paymenttype` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `purchases` CHANGE `paymenttype` `paymenttype` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `industrializations` CHANGE `databook` `databook` CHAR(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `industrializations` CHANGE `multa` `multa` CHAR(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `industrializations` CHANGE `inspecao` `inspecao` CHAR(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `industrializations` CHANGE `instalacao` `instalacao` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Tipo de Instalação';
ALTER TABLE `industrializations` CHANGE `certificado` `certificado` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'Certificado de matéria-prima; Certificado de Garantia; Certificado de calibração de equipamento.';
ALTER TABLE `industrializations` CHANGE `localEntrega` `localEntrega` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `industrializations` CHANGE `compraTerceiros` `compraTerceiros` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
